[package]
name = "image-recovery"
version = "0.1.0"
edition = "2021"
authors = ["Lílian Ferreira de Freitas <lily.mosquitoes@gmail.com>"]

[dependencies]
image = "0.24"
ndarray = "0.15"

[dev-dependencies]
pretty_assertions = "1"
rand = "0.8"
